import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/gradients.css";
import QueryProvider from "@/components/QueryProvider";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/nav/Footers/Footer";
import { Toaster } from "@/components/ui/sonner";
import { getSession } from "@/features/auth/getSession";
import SessionHydrator from "@/features/auth/components/SessionHydrator";
import Header from "@/components/nav/Headers/Header";
import AuthDialog from "@/features/auth/components/AuthDialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased app-shell min-h-screen flex flex-col overflow-x-hidden",
        )}
      >
        {/*TODO: this can probably be removed... Was trying to get the flashing of components to stop on reload*/}
        <SessionHydrator session={session} />
        {/* {session.isAuthenticated && <AuthenticatedHeader />} */}
        {/* <ClientProvider /> */}
        <QueryProvider>
          <>
            <Header />
            {children}
            <AuthDialog />
            <Footer />
          </>
        </QueryProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
